apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "demo-quarkus-app"
  annotations:
    argocd/app-name: demo-quarkus-app-dev
    backstage.io/kubernetes-id: demo-quarkus-app
    backstage.io/kubernetes-namespace: demo-quarkus-app-dev
    janus-idp.io/tekton-enabled : 'true'
    github.com/project-slug: janusdemo/demo-quarkus-app
    backstage.io/techdocs-ref: dir:.
  tags:
    - java
    - quarkus
  links:
    - url: https://devspaces.apps.cluster-88t78.88t78.sandbox2868.opentlc.com/#https://github.com/janusdemo/demo-quarkus-app?che-editor=che-incubator/che-code/insiders&devfilePath=.devfile-vscode.yaml
      title: CodeReady Workspaces (VS Code)
      icon: web
    - url: https://devspaces.apps.cluster-88t78.88t78.sandbox2868.opentlc.com/#https://github.com/janusdemo/demo-quarkus-app?che-editor=che-incubator/che-idea/latest&devfilePath=.devfile-intellij.yaml
      title: CodeReady Workspaces (JetBrains IntelliJ)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "group:default/quarkus dev team"
  providesApis:
    - "demo-quarkus-app"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "demo-quarkus-app"
spec:
  type: openapi
  lifecycle: production
  owner: "group:default/quarkus dev team"
  definition:
    $text: ./openapi.yaml